name: paroquia_sao_lourenco
description: App para uso gerencial e comunitário da Paróquia São Lourenço.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2+2
  flutter_modular: ^0.5.5
  expandable: ^4.1.2
  flutter_staggered_animations: ^0.1.2
  flutter_icons: ^1.0.0+1
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  firebase_storage: ^3.1.3
  cloud_firestore: ^0.13.4+2
  cached_network_image: ^2.0.0
  intl: ^0.16.1
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.2
  build_runner: ^1.8.0
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "dev_assets/icon-regular.png"


flutter:

  uses-material-design: true


  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Light.ttf
          weight: 300
        - asset: assets/fonts/Raleway-Medium.ttf
          weight: 500
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

    - family: CinzelDecorative
      fonts:
        - asset: assets/fonts/CinzelDecorative-Regular.ttf
          weight: 400
        - asset: assets/fonts/CinzelDecorative-Bold.ttf
          weight: 700
        - asset: assets/fonts/CinzelDecorative-Black.ttf
          weight: 900
        
          

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts:
  watch: flutter pub run build_runner watch --delete-conflicting-outputs